services:
  - type: web
    name: wali-bell-backend
    runtime: python
    repo: https://github.com/lostvoicex/wlbr.git
    branch: main
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && bash start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: APP_ENV
        value: "prod"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: "14"
      - key: CORS_ALLOW_ORIGINS
        value: "https://lostvoicex.github.io"
